version: '3.3'
services:

  soleman_backend:
    container_name: soleman_backend_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini

  server:
    container_name: nginx_app
    image: nginx:alpine
    ports:
      - 8010:80
      - 443:443
    volumes:
      - ./:/soleman
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/

  db:
    image: mysql:8.0
    container_name: db_app
    environment:
      MYSQL_DATABASE: soleman
      MYSQL_USER: soleman_user
      MYSQL_PASSWORD: my_passwd_user
      MYSQL_ROOT_PASSWORD: admin
#    volumes:
#      - ./dbdata:/var/lib/mysql
#      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - 3310:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_app
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3310
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80


#  soketi:
#    image: quay.io/soketi/soketi:0.17-16-alpine
#    ports:
#      - 6001:6001

